version: "3.1"

services:
  database:
    build:
       context: ./database
    image: pizzaria_db
    user: postgres
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: pizzaria
    ports:
      - "5432:5432"
    networks:
      - back-tier
    secrets:
      - postgres_password

  api:
    build:
       context: .
       dockerfile: Dockerfile
    image: pizzaria_api
    user: application
    ports:
      - "8080:8080"
    networks:
      - back-tier
    secrets:
      - postgres_password

networks:
  back-tier:

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
